CREATE TABLE email_templates (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject VARCHAR(128) NOT NULL,
  body text NOT NULL,
  created TIMESTAMP default current_timestamp NOT NULL
);

CREATE TABLE list_members (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(128) NOT NULL,
  last_name VARCHAR(128),
  company VARCHAR(128),
  position VARCHAR(128),
  created TIMESTAMP default current_timestamp NOT NULL,
  email VARCHAR(128) NOT NULL,
  identity int REFERENCES identities(id)
);

CREATE TABLE email_actions (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action CHAR(16) REFERENCES email_actions_enum(action) NOT NULL,
  created TIMESTAMP default current_timestamp NOT NULL,
  email_template_id int REFERENCES email_templates(id)
);

CREATE TABLE links (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL,
  created TIMESTAMP default current_timestamp NOT NULL
);

CREATE TABLE clicks (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id int REFERENCES links(id),
  created TIMESTAMP default current_timestamp NOT NULL
);

CREATE TABLE email_actions_enum (
  action CHAR(16) PRIMARY KEY
);

insert into email_actions_enum (action) VALUES ('sent'),('delivered'),('opened'),('clicked'),('hard_bounce'),('soft_bounce'),('complaint');

select * from email_actions_enum;

CREATE TABLE identities (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(128) NOT NULL
);

select * from email_list;

select * from email_templates;
select * from identities;

insert into email_templates (subject, body) VALUES ('foo', 'bar'), ('asdf','qwer');