# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/softside
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Download Dependencies
          command: go get -v -t -d ./...
      - run: 
          name: Run Tests
          command: go test -v ./tests/...
      - run: 
          name: Build Binaries
          command: |
            go build
            cd /go/src/softside/sendmail
            go build

      - run:
          name: Prepare To Save Binaries
          command: |
            gzip /go/src/softside/softside
            gzip /go/src/softside/sendmail/sendmail
            mv /go/src/softside/softside.gz /tmp/
            mv /go/src/softside/sendmail/sendmail.gz /tmp/

      - save_cache:
          key: softside-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/softside.gz
            - /tmp/sendmail.gz
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/softside
    steps:
      - restore_cache:
          key: softside-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Copy build output to server and restart the service
          command: |
            scp -o StrictHostKeyChecking=no /tmp/*.gz root@softsideoftech.com:
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'gunzip -f softside.gz'
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'gunzip -f sendmail.gz'
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'service softside restart'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master