# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/softside
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./tests/...
      - run: go build

      - run:
          name: Move build output to tmp file
          command: |
            gzip softside
            mv softside.gz /tmp/

      - store_artifacts:
          path: /tmp/softside.gz
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/softside
    steps:
      - checkout
      - run:
          name: Copy build output to server and restart the service
          command: |
            scp -o StrictHostKeyChecking=no /tmp/softside.gz root@softsideoftech.com:
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'gunzip -f softside.gz'
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'service softside restart'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master