package softmail

import "time"

type ListMember struct {
	Id           uint32
	FirstName    string
	LastName     string
	Company      string
	Position     string
	Email        string
	PersonalRole uint32
	Created      time.Time
}

type EmailTemplate struct {
	Id      int64
	Subject string
	Body    string
	Created time.Time
}

type SentEmail struct {
	Id              uint32
	EmailTemplateId int64
	ListMemberId    uint32
	Created         time.Time
}

type MemberCookie struct {
	Id           uint32
	ListMemberId uint32
	Created      time.Time
	Updated      time.Time
}

type TrackingHit struct {
	Id             uint32
	LinkId         uint32
	ListMemberId   uint32
	MemberCookieId uint32
	IpAddress      string
	ReferrerUrl    string
	Created        time.Time
}

/*
CREATE TABLE tracking_hits (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id        INT REFERENCES links (id)           NOT NULL,
  list_member_id INT REFERENCES list_members (id),
  cookie_id      INT REFERENCES member_cookies (id),
  ip_address     VARCHAR(128), --TODO: Change the IP Address type to something more appropriate
  referrer_url   VARCHAR(1024),
  created        TIMESTAMP DEFAULT current_timestamp NOT NULL
);

*/
